[files]
"https://timmy-io.github.io/monte-carlo/data/wortliste.txt" = "wortliste.txt"
"https://timmy-io.github.io/monte-carlo/data/wortliste_richtig.txt" = "wortliste_richtig.txt"
"https://timmy-io.github.io/monte-carlo/data/wortliste_historie.txt" = "wortliste_historie.txt"
